site_name: Water Course
site_url: https://water-course.github.io
nav:
  - Home: index.md
  - Content: content.md
  - Computer Labs: computer-lab.md
plugins:
  - mkdocs-jupyter:
      toc_depth: 2
      custom_mathjax_url: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=TeX-AMS_CHTML-full,Safe"
      include_source: True
theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/favicon.png
  palette:
    scheme: default
    primary: light blue
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: ''