[project]
name = "omega-github-io"
version = "0.1.0"
description = "The website for groundwater modelling"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-literate-nav>=0.6.1",
    "mkdocs-material>=9.6.5",
]