name: Build Slides with Quarkdown

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build-quarkdown-slides:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Prepare uv
        uses: astral-sh/setup-uv@v5

      - name: Clone quarkdown
        uses: GuillaumeFalourd/clone-github-repo-action@main
        with:
          owner: 'sghelichkhani'
          repository: 'quarkdown'

      - name: Build Quarkdown distribution
        run: |
          cd quarkdown
          ./gradlew build installDist

      - name: Add quarkdown to PATH
        run: echo "PATH=$PATH:/home/runner/work/EMSC3025/EMSC3025/quarkdown/build/install/quarkdown/bin/" >> $GITHUB_ENV

      - name: Set up Python
        run: uv python install
      - name: Building mkdocs
        run: |
          uv run mkdocs build --clean --site-dir site

      - name: Build slides with Quarkdown
        run: |
          cd slides
          make

      - uses: actions/upload-pages-artifact@v3
        with:
          path: site

      # - name: Upload built slides
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: slides-output
      #     path: output/