name: build_slides

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-quarkdown-slides:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Prepare uv
        uses: astral-sh/setup-uv@v5

      - name: Clone quarkdown
        uses: GuillaumeFalourd/clone-github-repo-action@main
        with:
          owner: 'sghelichkhani'
          repository: 'quarkdown'

      - name: Build Quarkdown distribution
        run: |
          cd quarkdown
          ./gradlew build installDist

      - name: Add quarkdown to PATH
        run: echo "PATH=$PATH:$GITHUB_WORKSPACE/quarkdown/build/install/quarkdown/bin/" >> $GITHUB_ENV

      - name: Get latest successful workflow run from tutorials
        id: get_run
        run: |
          response=$(curl -s \
            -H "Authorization: token ${{ secrets.TUTORIALSACCESS }}" \
            "https://api.github.com/repos/water-course/tutorials/actions/workflows/jupytext-conversion.yml/runs?status=success&per_page=1")
          run_id=$(echo "$response" | jq -r '.workflow_runs[0].id')
          echo $run_id
          echo "run_id=$run_id" >> $GITHUB_OUTPUT

      - name: Get artifact download URL
        id: get_artifact
        run: |
          artifacts=$(curl -s \
            -H "Authorization: token ${{ secrets.TUTORIALSACCESS }}" \
            "https://api.github.com/repos/water-course/tutorials/actions/runs/${{ steps.get_run.outputs.run_id }}/artifacts")

          download_url=$(echo "$artifacts" | jq -r '.artifacts[] | select(.name=="ready") | .archive_download_url')
          echo ${download_url}
          echo "download_url=$download_url" >> $GITHUB_OUTPUT

      - name: Download and unzip artifact
        run: |
          export TOKEN="${{ secrets.TUTORIALSACCESS }}"
          echo "Token present? ${TOKEN:0:4} ..."
          curl -L -H "Authorization: token ${{ secrets.TUTORIALSACCESS }}" \
            -o ready.zip "${{ steps.get_artifact.outputs.download_url }}"
          unzip ready.zip

      - name: List downloaded content
        run: |
          mkdir -p docs/computer-labs && mv -v *.ipynb docs/computer-labs/

      - uses: astral-sh/setup-uv@v5
      - name: Set up Python
        run: uv python install

      - name: Building mkdocs
        run: |
          uv run mkdocs build --clean --site-dir site

      - name: Build slides with Quarkdown
        run: |
          cd slides
          make


      - name: Upload built slides
        uses: actions/upload-pages-artifact@v3
        with:
          path: site


  deploy:
    runs-on: ubuntu-latest
    needs: build-quarkdown-slides
    if: github.ref == 'refs/heads/master'
    environment:
      name: github-pages
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
      - uses: actions/deploy-pages@v4
