name: Build Slides with Quarkdown

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build-quarkdown-slides:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Prepare uv
        uses: astral-sh/setup-uv@v5

      - name: Clone quarkdown
        uses: GuillaumeFalourd/clone-github-repo-action@main
        with:
          owner: 'sghelichkhani'
          repository: 'quarkdown'

      - name: Build Quarkdown distribution
        run: |
          cd quarkdown
          ./gradlew build installDist

      - name: Add quarkdown to PATH
        run: echo "PATH=$PATH:$GITHUB_WORKSPACE/quarkdown/build/install/quarkdown/bin/" >> $GITHUB_ENV

      - name: Set up Python
        run: uv python install

      - name: Install Python dependencies
        run: uv pip install mkdocs-material

      - name: Building mkdocs
        run: |
          uv run mkdocs build --clean --site-dir site

      - name: Build slides with Quarkdown
        run: |
          cd slides
          make

      - name: Upload built slides
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    runs-on: ubuntu-latest
    needs: build-quarkdown-slides
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
      - uses: actions/deploy-pages@v4
