on:
  workflow_dispatch:
    inputs:
      my_input:
        description: 'A custom input for the workflow'
        required: false
        default: 'default_value'

jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest successful workflow run from tutorials
        id: get_run
        run: |
          response=$(curl -s \
            -H "Authorization: token ${{ secrets.TUTORIALSACCESS }}" \
            "https://api.github.com/repos/water-course/water-course.github.io/actions/workflows/export.yml/runs?status=success&per_page=1")

          run_id=$(echo "$response" | jq -r '.workflow_runs[0].id')
          echo "run_id=$run_id" >> $GITHUB_OUTPUT

      - name: Get artifact download URL
        id: get_artifact
        run: |
          artifacts=$(curl -s \
            -H "Authorization: token ${{ secrets.TUTORIALSACCESS }}" \
            "https://api.github.com/repos/water-course/water-course.github.io/actions/runs/${{ steps.get_run.outputs.run_id }}/artifacts")

          download_url=$(echo "$artifacts" | jq -r '.artifacts[] | select(.name=="shared-folder") | .archive_download_url')
          echo "download_url=$download_url" >> $GITHUB_OUTPUT

      - name: Download and unzip artifact
        run: |
          curl -L -H "Authorization: token ${{ secrets.REPO_A_PAT }}" \
            -o ready "${{ steps.get_artifact.outputs.download_url }}"

      - name: List downloaded content
        run: ls 
